# See github.com/toml-lang/toml for a configuration guide
# enter the project name in square brackets
# project_id will be the last 16 chars of its SHA256
[credits]
# domain_id will be the last 16 chars of its SHA256
domain = 'elixir'
machines = [
  # minimal information, this machine will be considered started the moment the
  # information are parsed
  {ram = 128, cpus = 24},
  # machine will be considered booted at the given time, may be in the future
  {ram = 256, cpus = 20, existence = true},
  # considered online in between the two given timestamps
  {ram = 32, cpus = 15, existence = true},
]

[credits_2]
domain = 'elixir'
machines = [
  {ram=2, cpus=8, existence=true},
  {ram=4, cpus=8, existence=true},
]

[credits_3]
domain = 'elixir'
machines = [
  {ram = 8, cpus = 16},
  {ram = 128, cpus = 16}
]
