# See github.com/toml-lang/toml for a configuration guide
# enter the project name in square brackets
# project_id will be the last 16 chars of its SHA256
[admin]
# domain_id will be the last 16 chars of its SHA256
domain = 'domainA'
machines = [
  # minimal information, this machine will be considered started the moment the
  # information are parsed
  {ram = 1, cpus = 2},
  # machine will be considered booted at the given time, may be in the future
  {ram = 2, cpus = 2, uptime = 2018-11-26T14:30:00Z},
  # this machine is considered offline, will not be calculated
  # they are currently ignored, yet remain in case of changes
  {ram = 2, cpus = 2, uptime = false},
  # considered online in between the two given timestamps
  {ram = 8, cpus = 24, uptime = [2018-11-27T14:00:00Z, 2018-11-27T15:00:10Z]},
]

[demo]
domain = 'domainB'
machines = [
  {ram=2, cpus=8, uptime=true},
  {ram=4, cpus=8, uptime=true},
]

[TestProject]
domain = 'elixir'
machines = [
  {ram = 8, cpus = 16},
  {ram = 128, cpus = 16}
]
