# See github.com/toml-lang/toml for a configuration guide
# enter the project name in square brackets
# project_id will be its SHA256
[ProjectA]
domain = 'elixir'
# considered online in between the two given timestamps
machines = [
  {ram = 8, cpus = 8, existence = true},
  {ram = 8, cpus = 6, existence = [2018-11-27T14:00:00Z, 2018-12-27T15:00:10Z]},
]

[credits]
domain = 'elixir'
machines = [
  {ram=32, cpus=24, existence True},
]
