# See github.com/toml-lang/toml for a configuration guide
# enter the project name in square brackets
# project_id will be its SHA256
[DataTransfer]
domain = 'DomainA'
# minimal information, this machine will be considered started the moment the
# information are parsed
machines = [
  {ram=2048, cpus=2},
]

[PingTest]
domain = 'elixir'
machines = [
  {ram = 128, cpus = 1},
]
